# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017b03860dad135a55263d318f8eec6ef3894d7c43c2cb3f97a138511c7e43f62459c42361301f5b39ae8222b287c8a9fd7211c2679fef904ada6524104a6f16

test:
  secret_key_base: 945f02aa568dba36af426620bca8c0e2f155254b34d1bed0dfb55bfd800aea71a853ecf381765f721a1eee405e34764225eb83c018fff812c42139ad900e8682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
